/* Generated By:JavaCC: Do not edit this line. LConstants.java */
package parserOfL;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
public interface LConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT_CONSTANT = 8;
  /** RegularExpression Id. */
  int FLOAT_CONSTANT = 9;
  /** RegularExpression Id. */
  int STRING_CONSTANT = 10;
  /** RegularExpression Id. */
  int BOOL_CONSTANT = 11;
  /** RegularExpression Id. */
  int CHAR_CONSTANT = 12;
  /** RegularExpression Id. */
  int START = 13;
  /** RegularExpression Id. */
  int END = 14;
  /** RegularExpression Id. */
  int LET = 15;
  /** RegularExpression Id. */
  int SETQ = 16;
  /** RegularExpression Id. */
  int IF = 17;
  /** RegularExpression Id. */
  int MAP = 18;
  /** RegularExpression Id. */
  int REDUCE = 19;
  /** RegularExpression Id. */
  int PLUS = 20;
  /** RegularExpression Id. */
  int MINUS = 21;
  /** RegularExpression Id. */
  int MULTIPLY = 22;
  /** RegularExpression Id. */
  int DIVIDE = 23;
  /** RegularExpression Id. */
  int MOD = 24;
  /** RegularExpression Id. */
  int BIT_OR = 25;
  /** RegularExpression Id. */
  int BIT_XOR = 26;
  /** RegularExpression Id. */
  int BIT_COMPLEMENT = 27;
  /** RegularExpression Id. */
  int NT_EQ = 28;
  /** RegularExpression Id. */
  int LT = 29;
  /** RegularExpression Id. */
  int LT_EQ = 30;
  /** RegularExpression Id. */
  int GT_EQ = 31;
  /** RegularExpression Id. */
  int GT = 32;
  /** RegularExpression Id. */
  int DEFUN = 33;
  /** RegularExpression Id. */
  int LAMBDA = 34;
  /** RegularExpression Id. */
  int COMMA = 35;
  /** RegularExpression Id. */
  int ID = 36;
  /** RegularExpression Id. */
  int ALPHA = 37;
  /** RegularExpression Id. */
  int DIGIT = 38;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int InsideComment = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\";\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "<INT_CONSTANT>",
    "<FLOAT_CONSTANT>",
    "<STRING_CONSTANT>",
    "<BOOL_CONSTANT>",
    "<CHAR_CONSTANT>",
    "\"(\"",
    "\")\"",
    "\"let\"",
    "\"setq\"",
    "\"if\"",
    "\"map\"",
    "\"reduce\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"|\"",
    "\"^\"",
    "\"~\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\">\"",
    "\"defun\"",
    "\"lambda\"",
    "\",\"",
    "<ID>",
    "<ALPHA>",
    "<DIGIT>",
  };

}
